-- Give the remaining legacy Brevet upload table a stable row identifier.

alter table public.brevet_026
  add column if not exists __row_id bigint generated by default as identity;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.brevet_026'::regclass and contype = 'p'
  ) then
    alter table public.brevet_026 add primary key (__row_id);
  end if;
end;
$$;

analyze public.brevet_026;
