-- Give uploaded result tables a stable primary key and remove exact duplicate
-- indexes left by earlier speed migrations.

create or replace function public.create_results_upload_table(p_table_name text, p_columns text[])
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_column text;
  v_defs text := '';
  v_safe_columns text[] := array[]::text[];
  v_exists boolean;
  v_has_primary_key boolean;
begin
  if p_table_name is null or p_table_name !~ '^[A-Za-z_][A-Za-z0-9_]{1,62}$' then
    raise exception 'Invalid table name';
  end if;
  if p_columns is null or array_length(p_columns, 1) is null then
    raise exception 'At least one column is required';
  end if;

  foreach v_column in array p_columns loop
    v_column := btrim(v_column);
    if v_column <> ''
       and length(v_column) <= 120
       and v_column <> '__row_id'
       and not (v_column = any(v_safe_columns)) then
      v_safe_columns := array_append(v_safe_columns, v_column);
      v_defs := v_defs || case when v_defs = '' then '' else ', ' end || format('%I text', v_column);
    end if;
  end loop;
  if v_defs = '' then raise exception 'No valid columns supplied'; end if;

  select to_regclass(format('public.%I', p_table_name)) is not null into v_exists;
  if v_exists then
    execute format('truncate table public.%I', p_table_name);
    select exists (
      select 1 from pg_constraint
      where conrelid = to_regclass(format('public.%I', p_table_name)) and contype = 'p'
    ) into v_has_primary_key;
    if not v_has_primary_key then
      execute format('alter table public.%I add column if not exists __row_id bigint generated by default as identity', p_table_name);
      execute format('alter table public.%I add primary key (__row_id)', p_table_name);
    end if;
  else
    execute format('create table public.%I (__row_id bigint generated by default as identity primary key, %s)', p_table_name, v_defs);
  end if;

  execute format('alter table public.%I enable row level security', p_table_name);
  begin
    execute format(
      'create policy %I on public.%I for select to anon, authenticated using (true)',
      'public_read_' || substr(md5(p_table_name), 1, 12), p_table_name
    );
  exception when duplicate_object then null;
  end;

  execute format('grant select on public.%I to anon, authenticated', p_table_name);
  execute format('grant all on public.%I to service_role', p_table_name);
  execute format('grant usage, select on all sequences in schema public to service_role');

  return jsonb_build_object(
    'ok', true,
    'table', p_table_name,
    'columns', v_safe_columns,
    'reset_existing', v_exists,
    'primary_key', '__row_id'
  );
end;
$$;

revoke all on function public.create_results_upload_table(text,text[]) from public;
grant execute on function public.create_results_upload_table(text,text[]) to service_role;

do $$
declare
  e record;
  v_has_primary_key boolean;
begin
  for e in select distinct table_name from public.published_exams where table_name ~ '^[A-Za-z_][A-Za-z0-9_]{1,62}$' loop
    if to_regclass(format('public.%I', e.table_name)) is null then continue; end if;
    select exists (
      select 1 from pg_constraint
      where conrelid = to_regclass(format('public.%I', e.table_name)) and contype = 'p'
    ) into v_has_primary_key;
    if not v_has_primary_key then
      execute format('alter table public.%I add column if not exists __row_id bigint generated by default as identity', e.table_name);
      execute format('alter table public.%I add primary key (__row_id)', e.table_name);
    end if;
  end loop;
end;
$$;

-- Built-in tables: retain the deterministic v2 indexes and remove older copies.
drop index if exists public.bac_results_numero_idx;
drop index if exists public.idx_bac_results_wl_fast;
drop index if exists public.brevet_results_number_idx;
drop index if exists public.brevet_results_wilaya_idx;
drop index if exists public.brevet_results_centre_idx;
drop index if exists public.concours_results_numero_idx;
drop index if exists public.concours_results_wilaya_idx;
drop index if exists public.concours_results_moughataa_idx;
drop index if exists public.concours_results_centre_idx;
drop index if exists public.idx_concours_results_nodoss;
drop index if exists public.bac_session2_results_number_idx;
drop index if exists public.idx_bac_session2_results_wilaya_fast;
drop index if exists public.idx_bac_session2_results_centre_fast;
drop index if exists public.excellence_1as_results_number_idx;
drop index if exists public.idx_excellence_1as_results_wilaya_fast;
drop index if exists public.idx_excellence_1as_results_centre_fast;

-- 2026 uploaded tables: remove older exact copies and obsolete prefix indexes.
drop index if exists public.idx_27cf58031d77133f2462;
drop index if exists public.idx_642a5db8221e1443a21f;
drop index if exists public.idx_9565b0ffb9373a61300f;
drop index if exists public.idx_30da105fbb4c9501d3e9;
drop index if exists public.idx_3804aebcefb73438013a;
drop index if exists public.idx_40be3b6786dd1b4e3d89;
drop index if exists public.idx_148786bb61acdcc65553;
drop index if exists public.idx_bb38476ba727bdeaa6bd;
drop index if exists public.idx_e43e2eaa2c32ac9356d4;
drop index if exists public.idx_bce638f48b873fab613b;
drop index if exists public.idx_76b70ac8df89371ee7f9;
drop index if exists public.idx_1a7ae6a799a8063bfa3e;

analyze public.bac_results;
analyze public.brevet_results;
analyze public.concours_results;
analyze public.bac_session2_results;
analyze public.excellence_1as_results;
analyze public.brevet_2026;
analyze public.concour_2026;

notify pgrst, 'reload schema';
