-- Generic, data-driven competition candidature search.
-- Public users can only access the bounded RPCs below; the underlying tables
-- remain closed to anon/authenticated roles.

create table if not exists public.competitions (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name_ar text not null,
  name_fr text,
  authority_name text not null default 'اللجنة الوطنية للمسابقات',
  source_url text,
  current_stage text not null default 'temporary_admissibility',
  published_at timestamptz,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.competition_tracks (
  id bigint generated by default as identity primary key,
  competition_id bigint not null references public.competitions(id) on delete cascade,
  code text not null,
  name_ar text not null,
  name_fr text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (competition_id, code)
);

create or replace function public.normalize_candidature_name(p_value text)
returns text
language sql
immutable
strict
security invoker
set search_path = public
as $$
  select btrim(
    regexp_replace(
      translate(
        regexp_replace(lower(coalesce(p_value, '')), '[ًٌٍَُِّْـ]', '', 'g'),
        'أإآٱةىؤئ',
        'ااااهيوي'
      ),
      '\s+', ' ', 'g'
    )
  );
$$;

create table if not exists public.competition_candidatures (
  id bigint generated by default as identity primary key,
  competition_id bigint not null references public.competitions(id) on delete cascade,
  track_id bigint not null references public.competition_tracks(id) on delete cascade,
  receipt_number text not null,
  name_ar text not null,
  name_fr text,
  search_name text generated always as (
    public.normalize_candidature_name(coalesce(name_ar, '') || ' ' || coalesce(name_fr, ''))
  ) stored,
  status text not null,
  rejection_reason text,
  source_file text not null,
  source_sheet text not null,
  source_row integer not null,
  imported_at timestamptz not null default now(),
  constraint competition_candidatures_source_unique
    unique (competition_id, source_file, source_sheet, source_row)
);

create index if not exists competition_candidatures_receipt_idx
  on public.competition_candidatures (competition_id, track_id, receipt_number);
create index if not exists competition_candidatures_competition_receipt_idx
  on public.competition_candidatures (competition_id, receipt_number);
create index if not exists competition_candidatures_search_name_trgm_idx
  on public.competition_candidatures using gin (search_name extensions.gin_trgm_ops);
create index if not exists competition_tracks_public_order_idx
  on public.competition_tracks (competition_id, is_active, sort_order, id);

alter table public.competitions enable row level security;
alter table public.competition_tracks enable row level security;
alter table public.competition_candidatures enable row level security;

revoke all on table public.competitions from anon, authenticated;
revoke all on table public.competition_tracks from anon, authenticated;
revoke all on table public.competition_candidatures from anon, authenticated;

create or replace function public.get_public_competition_catalog()
returns table (
  slug text,
  name_ar text,
  name_fr text,
  authority_name text,
  source_url text,
  current_stage text,
  published_at timestamptz,
  tracks jsonb
)
language sql
stable
security definer
set search_path = public, extensions
as $$
  select
    c.slug,
    c.name_ar,
    c.name_fr,
    c.authority_name,
    c.source_url,
    c.current_stage,
    c.published_at,
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'code', t.code,
          'name_ar', t.name_ar,
          'name_fr', t.name_fr,
          'sort_order', t.sort_order
        ) order by t.sort_order, t.id
      ) filter (where t.id is not null),
      '[]'::jsonb
    ) as tracks
  from public.competitions c
  left join public.competition_tracks t
    on t.competition_id = c.id
   and t.is_active = true
  where c.is_published = true
  group by c.id
  order by c.published_at desc nulls last, c.id desc;
$$;

create or replace function public.search_public_competition_candidatures(
  p_competition_slug text,
  p_query text,
  p_mode text default 'name',
  p_track_code text default null,
  p_limit integer default 20
)
returns table (
  candidate_id bigint,
  receipt_number text,
  name_ar text,
  name_fr text,
  track_code text,
  track_name_ar text,
  status text,
  rejection_reason text,
  source_file text
)
language plpgsql
stable
security definer
set search_path = public, extensions
set statement_timeout = '3s'
as $$
declare
  v_competition_id bigint;
  v_query text := btrim(coalesce(p_query, ''));
  v_normalized_query text;
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 25);
begin
  select c.id into v_competition_id
  from public.competitions c
  where c.slug = btrim(coalesce(p_competition_slug, ''))
    and c.is_published = true
  limit 1;

  if v_competition_id is null then
    return;
  end if;

  if p_mode = 'receipt' then
    v_query := regexp_replace(v_query, '\s+', '', 'g');
    if v_query = '' or length(v_query) > 40 then
      return;
    end if;

    return query
      select r.id, r.receipt_number, r.name_ar, r.name_fr, t.code, t.name_ar,
             r.status, r.rejection_reason, r.source_file
      from public.competition_candidatures r
      join public.competition_tracks t on t.id = r.track_id
      where r.competition_id = v_competition_id
        and r.receipt_number = v_query
        and (coalesce(btrim(p_track_code), '') = '' or t.code = btrim(p_track_code))
      order by t.sort_order, r.id
      limit v_limit;
    return;
  end if;

  if p_mode <> 'name' then
    return;
  end if;

  v_normalized_query := public.normalize_candidature_name(v_query);
  if length(v_normalized_query) < 3 or length(v_normalized_query) > 120 then
    return;
  end if;

  return query
    select r.id, r.receipt_number, r.name_ar, r.name_fr, t.code, t.name_ar,
           r.status, r.rejection_reason, r.source_file
    from public.competition_candidatures r
    join public.competition_tracks t on t.id = r.track_id
    where r.competition_id = v_competition_id
      and r.search_name ilike '%' || v_normalized_query || '%'
      and (coalesce(btrim(p_track_code), '') = '' or t.code = btrim(p_track_code))
    order by extensions.similarity(r.search_name, v_normalized_query) desc,
             t.sort_order,
             r.id
    limit v_limit;
end;
$$;

revoke all on function public.get_public_competition_catalog() from public;
revoke all on function public.search_public_competition_candidatures(text, text, text, text, integer) from public;
grant execute on function public.get_public_competition_catalog() to anon, authenticated, service_role;
grant execute on function public.search_public_competition_candidatures(text, text, text, text, integer) to anon, authenticated, service_role;

-- Initial published competition data. Competition names stay in the database,
-- not in application code, so future competitions require data only.
insert into public.competitions (
  slug, name_ar, name_fr, authority_name, source_url,
  current_stage, published_at, is_published
)
values (
  'cnc-310-training-2026',
  'مسابقة خارجية لاكتتاب 310 عنصر للولوج لمدارس التكوين 2026',
  'Concours externe de recrutement de 310 unités pour l’accès à la formation aux écoles 2026',
  'اللجنة الوطنية للمسابقات',
  'https://www.cnc.gov.mr/VisAvisA.aspx?av=234AV1',
  'temporary_admissibility',
  '2026-08-18T00:56:00Z',
  true
)
on conflict (slug) do update set
  name_ar = excluded.name_ar,
  name_fr = excluded.name_fr,
  authority_name = excluded.authority_name,
  source_url = excluded.source_url,
  current_stage = excluded.current_stage,
  published_at = excluded.published_at,
  is_published = excluded.is_published,
  updated_at = now();

with c as (
  select id from public.competitions where slug = 'cnc-310-training-2026'
), seed(code, name_ar, sort_order) as (
  values
    ('1', 'كاتب ضبط رئيسي', 1),
    ('2', 'كتاب ضبط', 2),
    ('3', 'مفتش خزينة رئيسي', 3),
    ('4', 'مفتش ضرائب', 4),
    ('5', 'مراقب خزينة', 5),
    ('6', 'مراقب ضرائب', 6),
    ('7', 'قانونيون', 7),
    ('8', 'محرر إدارة', 8),
    ('9', 'مكون إشارة وبرايل', 9),
    ('10', 'مكون للترقية النسوية', 10),
    ('11', 'مراقب حدائق أطفال', 11),
    ('12', 'مفوض شباب', 12)
)
insert into public.competition_tracks (competition_id, code, name_ar, sort_order, is_active)
select c.id, seed.code, seed.name_ar, seed.sort_order, true
from c cross join seed
on conflict (competition_id, code) do update set
  name_ar = excluded.name_ar,
  sort_order = excluded.sort_order,
  is_active = true;

notify pgrst, 'reload schema';
