import React, { useEffect, useMemo, useState } from "react";
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Haptics from "expo-haptics";
import { LinearGradient } from "expo-linear-gradient";
import { useApp } from "../context/AppContext";
import { AppButton, Card, SectionTitle } from "../components/ui";

type SubjectRow = { id: string; name: string; mark: string; coefficient: string };
const STORAGE_KEY = "mr:calculator:v2";
const initialRows = (): SubjectRow[] => Array.from({ length: 5 }, (_, index) => ({ id: `subject-${index + 1}`, name: "", mark: "", coefficient: "1" }));
const parseNumber = (value: string) => { const number = Number(value.trim().replace(",", ".")); return Number.isFinite(number) ? number : Number.NaN; };

export function CalculatorScreen() {
  const { colors, language } = useApp();
  const [rows, setRows] = useState<SubjectRow[]>(initialRows);
  const [hydrated, setHydrated] = useState(false);
  const isAr = language === "ar";
  const labels = isAr ? {
    title: "حاسبة المعدل", eyebrow: "حساب فوري بالمعاملات", intro: "أدخل العلامة والمعامل لكل مادة. تُحفظ البيانات تلقائيًا على هاتفك.", placeholder: "مثال: الرياضيات", mark: "العلامة / 20", coefficient: "المعامل", add: "إضافة مادة", reset: "مسح الكل", result: "معدلك المحسوب", points: "النقاط الموزونة", totalCoefficients: "مجموع المعاملات", subjects: "المواد المحتسبة", empty: "أدخل علامتين صحيحتين على الأقل.", excellent: "ممتاز — واصل بنفس النسق", good: "جيد جدًا — بقي القليل للأفضل", pass: "معدل ناجح — ركز على المواد ذات المعامل الأكبر", improve: "تحتاج إلى خطة تحسين مركزة", note: "المعاملات قابلة للتعديل. راجع معاملات شعبتك الرسمية قبل اعتماد النتيجة.", delete: "حذف المادة"
  } : {
    title: "Calculateur de moyenne", eyebrow: "Calcul pondéré instantané", intro: "Saisissez la note et le coefficient de chaque matière. Les données sont enregistrées automatiquement.", placeholder: "Ex. Mathématiques", mark: "Note / 20", coefficient: "Coefficient", add: "Ajouter", reset: "Effacer", result: "Votre moyenne", points: "Points pondérés", totalCoefficients: "Coefficients", subjects: "Matières", empty: "Saisissez au moins deux notes valides.", excellent: "Excellent — continuez ainsi", good: "Très bien — proche du meilleur", pass: "Moyenne suffisante — priorisez les gros coefficients", improve: "Une amélioration ciblée est nécessaire", note: "Les coefficients sont modifiables. Vérifiez ceux de votre série avant toute décision.", delete: "Supprimer"
  };

  useEffect(() => { let active = true; AsyncStorage.getItem(STORAGE_KEY).then((value) => { if (!active || !value) return; const parsed = JSON.parse(value) as SubjectRow[]; if (Array.isArray(parsed) && parsed.length >= 2) setRows(parsed.slice(0, 20)); }).catch(() => undefined).finally(() => { if (active) setHydrated(true); }); return () => { active = false; }; }, []);
  useEffect(() => { if (!hydrated) return; const timer = setTimeout(() => { void AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(rows)); }, 250); return () => clearTimeout(timer); }, [hydrated, rows]);

  const calculation = useMemo(() => { const valid = rows.map((row) => ({ mark: parseNumber(row.mark), coefficient: parseNumber(row.coefficient) })).filter((row) => row.mark >= 0 && row.mark <= 20 && row.coefficient > 0); const totalCoefficients = valid.reduce((sum, row) => sum + row.coefficient, 0); const points = valid.reduce((sum, row) => sum + row.mark * row.coefficient, 0); return { count: valid.length, totalCoefficients, points, average: totalCoefficients ? points / totalCoefficients : Number.NaN }; }, [rows]);
  const validAverage = calculation.count >= 2 && Number.isFinite(calculation.average);
  const message = !validAverage ? labels.empty : calculation.average >= 16 ? labels.excellent : calculation.average >= 14 ? labels.good : calculation.average >= 10 ? labels.pass : labels.improve;
  const updateRow = (id: string, patch: Partial<SubjectRow>) => setRows((current) => current.map((row) => row.id === id ? { ...row, ...patch } : row));
  const addRow = () => { if (rows.length >= 20) return; setRows((current) => [...current, { id: `subject-${Date.now()}`, name: "", mark: "", coefficient: "1" }]); void Haptics.selectionAsync().catch(() => undefined); };
  const removeRow = (id: string) => { if (rows.length <= 2) return; setRows((current) => current.filter((row) => row.id !== id)); void Haptics.selectionAsync().catch(() => undefined); };
  const reset = () => { setRows(initialRows()); void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Warning).catch(() => undefined); };

  return <KeyboardAvoidingView style={[styles.root, { backgroundColor: colors.background }]} behavior={Platform.OS === "ios" ? "padding" : undefined}>
    <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
      <LinearGradient colors={["#0B3F29", "#106B41", "#1F8A58"]} style={styles.hero}><Text style={styles.heroIcon}>∑</Text><View style={{ flex: 1, alignItems: isAr ? "flex-end" : "flex-start" }}><Text style={styles.heroEyebrow}>{labels.eyebrow}</Text><Text style={styles.heroTitle}>{labels.title}</Text><Text style={[styles.heroText, { textAlign: isAr ? "right" : "left", writingDirection: isAr ? "rtl" : "ltr" }]}>{labels.intro}</Text></View></LinearGradient>
      <Card style={styles.resultCard}><Text style={[styles.resultLabel, { color: colors.muted }]}>{labels.result}</Text><Text style={[styles.resultValue, { color: validAverage ? colors.primary : colors.muted }]}>{validAverage ? calculation.average.toFixed(2) : "—"}</Text><Text style={[styles.resultMessage, { color: validAverage ? colors.text : colors.muted, writingDirection: isAr ? "rtl" : "ltr" }]}>{message}</Text><View style={styles.metrics}><View style={[styles.metric, { backgroundColor: colors.surfaceAlt }]}><Text style={[styles.metricValue, { color: colors.text }]}>{calculation.points.toFixed(2)}</Text><Text style={[styles.metricLabel, { color: colors.muted }]}>{labels.points}</Text></View><View style={[styles.metric, { backgroundColor: colors.surfaceAlt }]}><Text style={[styles.metricValue, { color: colors.text }]}>{calculation.totalCoefficients.toFixed(1).replace(/\.0$/, "")}</Text><Text style={[styles.metricLabel, { color: colors.muted }]}>{labels.totalCoefficients}</Text></View><View style={[styles.metric, { backgroundColor: colors.surfaceAlt }]}><Text style={[styles.metricValue, { color: colors.text }]}>{calculation.count}</Text><Text style={[styles.metricLabel, { color: colors.muted }]}>{labels.subjects}</Text></View></View></Card>
      <SectionTitle title={labels.title} />
      <View style={styles.rows}>{rows.map((row, index) => <View key={row.id} style={[styles.subjectCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.subjectHeader, { flexDirection: isAr ? "row-reverse" : "row" }]}><View style={[styles.index, { backgroundColor: colors.primarySoft }]}><Text style={[styles.indexText, { color: colors.primary }]}>{index + 1}</Text></View><TextInput value={row.name} onChangeText={(name) => updateRow(row.id, { name })} placeholder={labels.placeholder} placeholderTextColor={colors.muted} style={[styles.nameInput, { color: colors.text, backgroundColor: colors.surfaceAlt, borderColor: colors.border, textAlign: isAr ? "right" : "left", writingDirection: isAr ? "rtl" : "ltr" }]} /><Pressable accessibilityLabel={labels.delete} disabled={rows.length <= 2} onPress={() => removeRow(row.id)} style={[styles.delete, { backgroundColor: `${colors.danger}14`, opacity: rows.length <= 2 ? .25 : 1 }]}><Text style={[styles.deleteText, { color: colors.danger }]}>×</Text></Pressable></View><View style={[styles.inputRow, { flexDirection: isAr ? "row-reverse" : "row" }]}><View style={styles.group}><Text style={[styles.label, { color: colors.muted, textAlign: isAr ? "right" : "left" }]}>{labels.mark}</Text><TextInput value={row.mark} onChangeText={(mark) => updateRow(row.id, { mark })} keyboardType="decimal-pad" placeholder="0 - 20" placeholderTextColor={colors.muted} maxLength={5} style={[styles.numberInput, { color: colors.text, backgroundColor: colors.surfaceAlt, borderColor: colors.border }]} /></View><View style={styles.group}><Text style={[styles.label, { color: colors.muted, textAlign: isAr ? "right" : "left" }]}>{labels.coefficient}</Text><TextInput value={row.coefficient} onChangeText={(coefficient) => updateRow(row.id, { coefficient })} keyboardType="decimal-pad" placeholder="1" placeholderTextColor={colors.muted} maxLength={4} style={[styles.numberInput, { color: colors.text, backgroundColor: colors.surfaceAlt, borderColor: colors.border }]} /></View></View></View>)}</View>
      <View style={styles.actions}><AppButton title={labels.add} variant="secondary" onPress={addRow} style={styles.action} /><AppButton title={labels.reset} variant="ghost" onPress={reset} style={styles.action} /></View>
      <View style={[styles.note, { backgroundColor: `${colors.gold}14`, borderColor: `${colors.gold}45` }]}><Text style={[styles.noteIcon, { color: colors.gold }]}>!</Text><Text style={[styles.noteText, { color: colors.muted, textAlign: isAr ? "right" : "left", writingDirection: isAr ? "rtl" : "ltr" }]}>{labels.note}</Text></View>
    </ScrollView>
  </KeyboardAvoidingView>;
}

const styles = StyleSheet.create({ root: { flex: 1 }, content: { padding: 14, paddingBottom: 112 }, hero: { borderRadius: 27, padding: 20, flexDirection: "row", gap: 14, alignItems: "center", marginBottom: 13 }, heroIcon: { width: 60, color: "#FFF", fontSize: 40, fontWeight: "900", textAlign: "center" }, heroEyebrow: { color: "#D7F6E5", fontSize: 9, fontWeight: "900" }, heroTitle: { color: "#FFF", marginTop: 3, fontSize: 22, fontWeight: "900" }, heroText: { color: "rgba(255,255,255,.77)", marginTop: 5, fontSize: 10, lineHeight: 17, fontWeight: "700" }, resultCard: { alignItems: "center", marginBottom: 21 }, resultLabel: { fontSize: 10, fontWeight: "900" }, resultValue: { marginTop: 4, fontSize: 47, lineHeight: 58, fontWeight: "900" }, resultMessage: { fontSize: 10, lineHeight: 17, fontWeight: "800", textAlign: "center" }, metrics: { width: "100%", flexDirection: "row", gap: 7, marginTop: 15 }, metric: { flex: 1, minHeight: 75, borderRadius: 16, alignItems: "center", justifyContent: "center", padding: 6 }, metricValue: { fontSize: 14, fontWeight: "900" }, metricLabel: { marginTop: 5, fontSize: 8, fontWeight: "800", textAlign: "center" }, rows: { gap: 10 }, subjectCard: { borderWidth: 1, borderRadius: 21, padding: 12 }, subjectHeader: { gap: 8, alignItems: "center" }, index: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center" }, indexText: { fontSize: 13, fontWeight: "900" }, nameInput: { flex: 1, minHeight: 44, borderWidth: 1, borderRadius: 14, paddingHorizontal: 12, fontSize: 12, fontWeight: "800" }, delete: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center" }, deleteText: { fontSize: 24, lineHeight: 26 }, inputRow: { gap: 9, marginTop: 10 }, group: { flex: 1 }, label: { fontSize: 9, fontWeight: "800", marginBottom: 5 }, numberInput: { minHeight: 47, borderWidth: 1, borderRadius: 14, paddingHorizontal: 10, fontSize: 15, fontWeight: "900", textAlign: "center" }, actions: { flexDirection: "row", gap: 9, marginTop: 12 }, action: { flex: 1 }, note: { borderWidth: 1, borderRadius: 17, padding: 12, flexDirection: "row", alignItems: "center", gap: 9, marginTop: 12 }, noteIcon: { width: 24, fontSize: 18, fontWeight: "900", textAlign: "center" }, noteText: { flex: 1, fontSize: 9, lineHeight: 16, fontWeight: "700" } });
