import React, { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import { useApp } from "../context/AppContext";
import { LESSONS, type Lesson } from "../data/lessons";
import { EmptyState, Pill, SectionTitle } from "../components/ui";

export function LessonsScreen({ onOpen }: { onOpen: (lesson: Lesson) => void }) {
  const { colors, language } = useApp();
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("all");
  const isAr = language === "ar";
  const labels = isAr ? { title: "الدروس والملخصات", subtitle: "محتوى مراجعة مختصر يعمل دون اتصال", search: "ابحث عن درس أو مادة", all: "الكل", minutes: "دقيقة", empty: "لا يوجد درس مطابق.", offline: "متاح دون اتصال", open: "فتح الدرس" } : { title: "Cours et fiches", subtitle: "Des révisions courtes disponibles hors ligne", search: "Rechercher un cours ou une matière", all: "Tous", minutes: "min", empty: "Aucun cours correspondant.", offline: "Hors ligne", open: "Ouvrir" };
  const categories = useMemo(() => ["all", ...Array.from(new Set(LESSONS.map((lesson) => isAr ? lesson.categoryAr : lesson.categoryFr)))], [isAr]);
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return LESSONS.filter((lesson) => { const lessonCategory = isAr ? lesson.categoryAr : lesson.categoryFr; const haystack = `${lesson.titleAr} ${lesson.titleFr} ${lesson.summaryAr} ${lesson.summaryFr} ${lesson.keywords.join(" ")}`.toLowerCase(); return (category === "all" || category === lessonCategory) && (!q || haystack.includes(q)); }); }, [category, isAr, query]);

  return <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
    <LinearGradient colors={["#143A68", "#285D9E", "#4779BE"]} style={styles.hero}><View style={styles.heroIcon}><Text style={styles.heroIconText}>▤</Text></View><View style={{ flex: 1, alignItems: isAr ? "flex-end" : "flex-start" }}><Text style={styles.heroTitle}>{labels.title}</Text><Text style={[styles.heroSubtitle, { textAlign: isAr ? "right" : "left", writingDirection: isAr ? "rtl" : "ltr" }]}>{labels.subtitle}</Text><View style={styles.offlinePill}><Text style={styles.offlineText}>{labels.offline}</Text></View></View></LinearGradient>
    <TextInput value={query} onChangeText={setQuery} placeholder={labels.search} placeholderTextColor={colors.muted} style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border, color: colors.text, textAlign: isAr ? "right" : "left", writingDirection: isAr ? "rtl" : "ltr" }]} />
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.categories}>{categories.map((item) => { const active = category === item; return <Pressable key={item} onPress={() => setCategory(item)} style={[styles.category, { backgroundColor: active ? colors.primary : colors.surface, borderColor: active ? colors.primary : colors.border }]}><Text style={[styles.categoryText, { color: active ? "#FFF" : colors.text }]}>{item === "all" ? labels.all : item}</Text></Pressable>; })}</ScrollView>
    <SectionTitle title={labels.title} action={<Pill text={`${filtered.length}`} tone="green" />} />
    {filtered.length ? <View style={styles.list}>{filtered.map((lesson) => { const title = isAr ? lesson.titleAr : lesson.titleFr; const summary = isAr ? lesson.summaryAr : lesson.summaryFr; const lessonCategory = isAr ? lesson.categoryAr : lesson.categoryFr; return <Pressable key={lesson.id} onPress={() => onOpen(lesson)} style={({ pressed }) => [styles.card, { backgroundColor: colors.surface, borderColor: colors.border, shadowColor: colors.shadow, opacity: pressed ? .8 : 1 }]}><View style={[styles.cardTop, { flexDirection: isAr ? "row-reverse" : "row" }]}><View style={[styles.lessonIcon, { backgroundColor: colors.primarySoft }]}><Text style={[styles.lessonIconText, { color: colors.primary }]}>{lesson.icon}</Text></View><View style={{ flex: 1, alignItems: isAr ? "flex-end" : "flex-start" }}><Text style={[styles.lessonCategory, { color: colors.primary }]}>{lessonCategory}</Text><Text style={[styles.lessonTitle, { color: colors.text, writingDirection: isAr ? "rtl" : "ltr" }]}>{title}</Text></View><Text style={[styles.chevron, { color: colors.muted }]}>{isAr ? "‹" : "›"}</Text></View><Text style={[styles.summary, { color: colors.muted, textAlign: isAr ? "right" : "left", writingDirection: isAr ? "rtl" : "ltr" }]}>{summary}</Text><View style={[styles.footer, { flexDirection: isAr ? "row-reverse" : "row" }]}><Pill text={`${lesson.duration} ${labels.minutes}`} tone="gold" /><Text style={[styles.open, { color: colors.primary }]}>{labels.open}</Text></View></Pressable>; })}</View> : <EmptyState icon="📚" title={labels.empty} />}
  </ScrollView>;
}

const styles = StyleSheet.create({ content: { padding: 14, paddingBottom: 112 }, hero: { borderRadius: 27, padding: 20, flexDirection: "row", alignItems: "center", gap: 14, marginBottom: 13 }, heroIcon: { width: 66, height: 66, borderRadius: 21, backgroundColor: "rgba(255,255,255,.14)", alignItems: "center", justifyContent: "center" }, heroIconText: { color: "#FFF", fontSize: 30, fontWeight: "900" }, heroTitle: { color: "#FFF", fontSize: 22, fontWeight: "900" }, heroSubtitle: { color: "rgba(255,255,255,.77)", marginTop: 5, fontSize: 10, lineHeight: 17, fontWeight: "700" }, offlinePill: { marginTop: 9, backgroundColor: "rgba(255,255,255,.15)", paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999 }, offlineText: { color: "#FFF", fontSize: 8, fontWeight: "900" }, search: { minHeight: 53, borderWidth: 1, borderRadius: 17, paddingHorizontal: 15, fontSize: 13, fontWeight: "800", marginBottom: 10 }, categories: { gap: 7, paddingBottom: 16 }, category: { minHeight: 39, borderWidth: 1, borderRadius: 14, paddingHorizontal: 12, alignItems: "center", justifyContent: "center" }, categoryText: { fontSize: 10, fontWeight: "900" }, list: { gap: 10 }, card: { borderWidth: 1, borderRadius: 22, padding: 14, shadowOpacity: .05, shadowOffset: { width: 0, height: 7 }, shadowRadius: 16, elevation: 1 }, cardTop: { gap: 11, alignItems: "center" }, lessonIcon: { width: 49, height: 49, borderRadius: 16, alignItems: "center", justifyContent: "center" }, lessonIconText: { fontSize: 17, fontWeight: "900" }, lessonCategory: { fontSize: 8, fontWeight: "900", marginBottom: 3 }, lessonTitle: { fontSize: 14, lineHeight: 21, fontWeight: "900" }, chevron: { fontSize: 28 }, summary: { marginTop: 11, fontSize: 10, lineHeight: 17, fontWeight: "700" }, footer: { marginTop: 12, alignItems: "center", justifyContent: "space-between" }, open: { fontSize: 9, fontWeight: "900" } });
