import React, { useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, Share, StyleSheet, Text, View } from "react-native";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import * as Haptics from "expo-haptics";
import { useApp } from "../context/AppContext";
import { getPrimaryFields, resultPdfHtml, resultShareText, textValue, trackText } from "../lib/result";
import { t } from "../lib/i18n";
import type { Exam, ResultRow } from "../types";
import { AppButton, Card, Pill } from "../components/ui";

export function ResultDetailsScreen({ exam, row, onBack }: { exam: Exam; row: ResultRow; onBack: () => void }) {
  const { colors, language, saveResult, removeSaved, isSaved } = useApp(); const [exporting, setExporting] = useState(false); const saved = isSaved(exam, row); const fields = useMemo(() => getPrimaryFields(exam, row), [exam, row]);
  const mainRows = [[t(language, "candidate"), fields.name], [t(language, "number"), fields.number], [t(language, "score"), fields.score], [t(language, "decision"), fields.decision], ...(fields.track ? [[t(language, "track"), trackText(fields.track, language)]] : []), ...(fields.rank ? [[t(language, "rank"), fields.rank]] : []), ...(fields.wilaya ? [[t(language, "wilaya"), fields.wilaya]] : []), ...(fields.moughataa ? [[t(language, "moughataa"), fields.moughataa]] : []), ...(fields.school ? [[t(language, "school"), fields.school]] : []), ...(fields.centre ? [[t(language, "centre"), fields.centre]] : []), ...(fields.birthPlace ? [[t(language, "birthPlace"), fields.birthPlace]] : []), ...(fields.birthDate ? [[t(language, "birthDate"), fields.birthDate]] : [])] as Array<[string, unknown]>;
  const shownKeys = new Set([exam.name_column, exam.number_column, exam.score_column, exam.decision_column, exam.track_column, exam.wilaya_column, exam.moughataa_column, exam.school_column, exam.centre_column, exam.birth_place_column, exam.birth_date_column, "rank"].filter(Boolean));
  const extraRows = Object.entries(row).filter(([key, value]) => !shownKeys.has(key) && value !== null && value !== undefined && value !== "").slice(0, 20);
  async function toggleSaved() { if (saved) await removeSaved(`${exam.source_key}:${textValue(fields.number)}:${textValue(fields.name)}`); else { await saveResult(exam, row); Alert.alert(t(language, "saved"), t(language, "savedDone")); } }
  async function shareResult() { await Haptics.selectionAsync().catch(() => undefined); await Share.share({ message: resultShareText(exam, row, language) }); }
  async function exportPdf() { setExporting(true); try { const file = await Print.printToFileAsync({ html: resultPdfHtml(exam, row, language), base64: false }); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(file.uri, { mimeType: "application/pdf", dialogTitle: t(language, "pdf"), UTI: "com.adobe.pdf" }); else Alert.alert(t(language, "pdf"), t(language, "downloadedPdf")); await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(() => undefined); } catch { Alert.alert(t(language, "error")); } finally { setExporting(false); } }
  return <View style={[styles.root, { backgroundColor: colors.background }]}><View style={[styles.header, { backgroundColor: colors.surface, borderColor: colors.border, flexDirection: language === "ar" ? "row-reverse" : "row" }]}><Pressable onPress={onBack} style={[styles.backButton, { backgroundColor: colors.surfaceAlt }]}><Text style={[styles.backText, { color: colors.text }]}>{language === "ar" ? "→" : "←"}</Text></Pressable><View style={{ flex: 1, alignItems: language === "ar" ? "flex-end" : "flex-start" }}><Text style={[styles.headerKicker, { color: colors.primary }]}>{t(language, "details")}</Text><Text style={[styles.headerTitle, { color: colors.text }]} numberOfLines={1}>{language === "ar" ? exam.title_ar : exam.title_fr}</Text></View>{saved ? <Text style={[styles.star, { color: colors.gold }]}>★</Text> : null}</View>
    <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Card style={styles.identityCard}><View style={[styles.avatar, { backgroundColor: colors.primarySoft }]}><Text style={[styles.avatarText, { color: colors.primary }]}>{String(textValue(fields.name)).slice(0, 1).toUpperCase()}</Text></View><Text style={[styles.candidateName, { color: colors.text, writingDirection: language === "ar" ? "rtl" : "ltr" }]}>{textValue(fields.name)}</Text><Text style={[styles.candidateNumber, { color: colors.muted }]}>#{textValue(fields.number)}</Text><View style={styles.identityPills}><Pill text={textValue(fields.decision)} tone={/admis|ناجح|مقبول/i.test(textValue(fields.decision)) ? "green" : "neutral"} />{fields.rank ? <Pill text={`#${textValue(fields.rank)}`} tone="gold" /> : null}</View></Card>
      <Card style={styles.detailCard}>{mainRows.map(([label, value], index) => <View key={`${label}:${index}`} style={[styles.detailRow, { borderBottomColor: colors.border, flexDirection: language === "ar" ? "row-reverse" : "row" }]}><Text style={[styles.detailLabel, { color: colors.muted, textAlign: language === "ar" ? "right" : "left" }]}>{label}</Text><Text style={[styles.detailValue, { color: colors.text, textAlign: language === "ar" ? "left" : "right", writingDirection: language === "ar" ? "rtl" : "ltr" }]}>{textValue(value)}</Text></View>)}</Card>
      <View style={styles.actions}><AppButton title={saved ? t(language, "remove") : t(language, "save")} variant={saved ? "danger" : "primary"} onPress={() => void toggleSaved()} style={styles.actionButton} /><AppButton title={t(language, "share")} variant="secondary" onPress={() => void shareResult()} style={styles.actionButton} /><AppButton title={t(language, "pdf")} variant="ghost" loading={exporting} onPress={() => void exportPdf()} style={styles.fullButton} /></View>
      {extraRows.length ? <Card><Text style={[styles.extraTitle, { color: colors.text, textAlign: language === "ar" ? "right" : "left" }]}>{t(language, "allFields")}</Text>{extraRows.map(([key, value]) => <View key={key} style={[styles.detailRow, { borderBottomColor: colors.border, flexDirection: language === "ar" ? "row-reverse" : "row" }]}><Text style={[styles.detailLabel, { color: colors.muted }]} numberOfLines={1}>{key}</Text><Text style={[styles.detailValue, { color: colors.text }]} numberOfLines={3}>{textValue(value)}</Text></View>)}</Card> : null}
    </ScrollView>
  </View>;
}
const styles = StyleSheet.create({ root: { flex: 1 }, header: { minHeight: 68, alignItems: "center", gap: 12, borderBottomWidth: 1, paddingHorizontal: 14, paddingVertical: 10 }, backButton: { width: 44, height: 44, borderRadius: 15, alignItems: "center", justifyContent: "center" }, backText: { fontSize: 22, fontWeight: "900" }, headerKicker: { fontSize: 9, fontWeight: "900" }, headerTitle: { marginTop: 3, fontSize: 15, fontWeight: "900" }, star: { fontSize: 22 }, content: { padding: 14, paddingBottom: 42, gap: 12 }, identityCard: { alignItems: "center", paddingVertical: 24 }, avatar: { width: 68, height: 68, borderRadius: 24, alignItems: "center", justifyContent: "center" }, avatarText: { fontSize: 28, fontWeight: "900" }, candidateName: { marginTop: 14, fontSize: 20, lineHeight: 29, fontWeight: "900", textAlign: "center" }, candidateNumber: { marginTop: 5, fontSize: 12, fontWeight: "800" }, identityPills: { flexDirection: "row", flexWrap: "wrap", gap: 8, justifyContent: "center", marginTop: 13 }, detailCard: { paddingVertical: 5 }, detailRow: { minHeight: 51, alignItems: "center", justifyContent: "space-between", gap: 15, borderBottomWidth: StyleSheet.hairlineWidth, paddingVertical: 11 }, detailLabel: { flex: 0.9, fontSize: 11, fontWeight: "800" }, detailValue: { flex: 1.35, fontSize: 12, fontWeight: "900" }, actions: { flexDirection: "row", flexWrap: "wrap", gap: 9 }, actionButton: { flex: 1, minWidth: 145 }, fullButton: { width: "100%" }, extraTitle: { fontSize: 15, fontWeight: "900", marginBottom: 5 } });
