import React, { useEffect, useRef, useState } from "react";
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import * as Haptics from "expo-haptics";
import { useApp } from "../context/AppContext";
import { searchResults } from "../lib/api";
import { t } from "../lib/i18n";
import type { Exam, ResultRow } from "../types";
import { ExamCard } from "../components/ExamCard";
import { ResultCard } from "../components/ResultCard";
import { AppButton, EmptyState, Pill } from "../components/ui";

export function SearchScreen({ exam, initialQuery, onBack, onDetails }: { exam: Exam; initialQuery?: string; onBack: () => void; onDetails: (row: ResultRow, query: string) => void; }) {
  const { colors, language, addHistory, isOnline } = useApp(); const [query, setQuery] = useState(initialQuery || ""); const [rows, setRows] = useState<ResultRow[]>([]); const [loading, setLoading] = useState(false); const [searched, setSearched] = useState(false); const [error, setError] = useState(""); const autoSearched = useRef(false);
  async function runSearch() { const value = query.trim(); if (!value || loading) return; setLoading(true); setError(""); setSearched(true); try { const resultRows = await searchResults(exam.source_key, value); setRows(resultRows); await addHistory({ id: `${Date.now()}:${exam.source_key}:${value}`, source: exam.source_key, titleAr: exam.title_ar, titleFr: exam.title_fr, query: value, resultCount: resultRows.length, searchedAt: new Date().toISOString() }); await Haptics.impactAsync(resultRows.length ? Haptics.ImpactFeedbackStyle.Light : Haptics.ImpactFeedbackStyle.Soft).catch(() => undefined); } catch { setRows([]); setError(t(language, "error")); } finally { setLoading(false); } }
  useEffect(() => { if (initialQuery && !autoSearched.current) { autoSearched.current = true; void runSearch(); } }, []);
  return <KeyboardAvoidingView style={[styles.root, { backgroundColor: colors.background }]} behavior={Platform.OS === "ios" ? "padding" : undefined}>
    <View style={[styles.header, { backgroundColor: colors.surface, borderColor: colors.border, flexDirection: language === "ar" ? "row-reverse" : "row" }]}><Pressable onPress={onBack} style={[styles.backButton, { backgroundColor: colors.surfaceAlt }]}><Text style={[styles.backText, { color: colors.text }]}>{language === "ar" ? "→" : "←"}</Text></Pressable><View style={{ flex: 1, alignItems: language === "ar" ? "flex-end" : "flex-start" }}><Text style={[styles.headerKicker, { color: colors.primary }]}>{t(language, "searchTitle")}</Text><Text style={[styles.headerTitle, { color: colors.text, writingDirection: language === "ar" ? "rtl" : "ltr" }]} numberOfLines={1}>{language === "ar" ? exam.title_ar : exam.title_fr}</Text></View></View>
    <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><ExamCard exam={exam} onPress={() => undefined} compact />
      {!isOnline ? <View style={[styles.notice, { borderColor: `${colors.gold}55`, backgroundColor: `${colors.gold}18` }]}><Text style={[styles.noticeText, { color: colors.gold }]}>{t(language, "offline")}</Text></View> : null}
      <View style={[styles.searchBox, { backgroundColor: colors.surface, borderColor: colors.border }]}><TextInput value={query} onChangeText={setQuery} placeholder={t(language, "searchPlaceholder")} placeholderTextColor={colors.muted} returnKeyType="search" onSubmitEditing={() => void runSearch()} autoCapitalize="none" autoCorrect={false} style={[styles.input, { backgroundColor: colors.surfaceAlt, color: colors.text, borderColor: colors.border, textAlign: language === "ar" ? "right" : "left", writingDirection: language === "ar" ? "rtl" : "ltr" }]} /><AppButton title={t(language, "search")} loading={loading} onPress={() => void runSearch()} disabled={!query.trim() || !isOnline} /></View>
      {error ? <View style={[styles.notice, { borderColor: `${colors.danger}55`, backgroundColor: `${colors.danger}15` }]}><Text style={[styles.noticeText, { color: colors.danger }]}>{error}</Text></View> : null}
      <View style={[styles.resultsHeader, { flexDirection: language === "ar" ? "row-reverse" : "row" }]}><Text style={[styles.resultsTitle, { color: colors.text }]}>{searched ? `${rows.length} ${t(language, "resultsFound")}` : t(language, "typeQuery")}</Text>{searched && rows.length ? <Pill text={`${rows.length}`} tone="green" /> : null}</View>
      {loading ? <View style={styles.loadingBox}><ActivityIndicator size="large" color={colors.primary} /><Text style={[styles.loadingText, { color: colors.muted }]}>{t(language, "loading")}</Text></View> : null}
      {!loading && searched && !rows.length && !error ? <EmptyState icon="🔎" title={t(language, "noResults")} /> : null}
      {!loading && rows.length ? <View style={styles.list}>{rows.map((row, index) => <ResultCard key={`${exam.source_key}:${index}:${JSON.stringify(row).slice(0, 40)}`} exam={exam} row={row} onPress={() => onDetails(row, query.trim())} />)}</View> : null}
    </ScrollView>
  </KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ root: { flex: 1 }, header: { minHeight: 68, alignItems: "center", gap: 12, borderBottomWidth: 1, paddingHorizontal: 14, paddingVertical: 10 }, backButton: { width: 44, height: 44, borderRadius: 15, alignItems: "center", justifyContent: "center" }, backText: { fontSize: 22, fontWeight: "900" }, headerKicker: { fontSize: 9, fontWeight: "900" }, headerTitle: { marginTop: 3, fontSize: 15, fontWeight: "900" }, content: { padding: 14, paddingBottom: 40, gap: 13 }, searchBox: { borderWidth: 1, borderRadius: 22, padding: 13, gap: 10 }, input: { minHeight: 54, borderWidth: 1, borderRadius: 16, paddingHorizontal: 15, fontSize: 15, fontWeight: "700" }, notice: { borderWidth: 1, borderRadius: 15, padding: 11 }, noticeText: { fontSize: 11, fontWeight: "800", textAlign: "center", lineHeight: 18 }, resultsHeader: { alignItems: "center", justifyContent: "space-between", gap: 10, marginTop: 5 }, resultsTitle: { flex: 1, fontSize: 14, fontWeight: "900" }, loadingBox: { paddingVertical: 30, alignItems: "center", gap: 10 }, loadingText: { fontSize: 11, fontWeight: "800" }, list: { gap: 11 } });
