import React from "react";
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { useApp } from "../context/AppContext";
import { t } from "../lib/i18n";
import type { Language, ThemeMode } from "../types";
import { Card, SectionTitle } from "../components/ui";

function ChoiceRow<T extends string>({ values, active, labels, onChange }: { values: T[]; active: T; labels: Record<T, string>; onChange: (value: T) => void }) { const { colors } = useApp(); return <View style={styles.choices}>{values.map((value) => { const selected = value === active; return <Pressable key={value} onPress={() => onChange(value)} style={[styles.choice, { backgroundColor: selected ? colors.primary : colors.surfaceAlt, borderColor: selected ? colors.primary : colors.border }]}><Text style={[styles.choiceText, { color: selected ? "#FFFFFF" : colors.text }]}>{labels[value]}</Text></Pressable>; })}</View>; }
export function SettingsScreen() {
  const { colors, language, settings, setLanguage, setThemeMode, setNotificationsEnabled } = useApp();
  const languageLabels: Record<Language, string> = { ar: "العربية", fr: "Français" }; const themeLabels: Record<ThemeMode, string> = { system: t(language, "system"), light: t(language, "light"), dark: t(language, "dark") };
  return <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><SectionTitle title={t(language, "settings")} />
    <Card style={styles.cardGap}><Text style={[styles.settingTitle, { color: colors.text, textAlign: language === "ar" ? "right" : "left" }]}>{t(language, "language")}</Text><ChoiceRow values={["ar", "fr"]} active={settings.language} labels={languageLabels} onChange={(value) => void setLanguage(value)} /></Card>
    <Card style={styles.cardGap}><Text style={[styles.settingTitle, { color: colors.text, textAlign: language === "ar" ? "right" : "left" }]}>{t(language, "appearance")}</Text><ChoiceRow values={["system", "light", "dark"]} active={settings.themeMode} labels={themeLabels} onChange={(value) => void setThemeMode(value)} /></Card>
    <Card style={styles.cardGap}><View style={[styles.switchRow, { flexDirection: language === "ar" ? "row-reverse" : "row" }]}><View style={{ flex: 1, alignItems: language === "ar" ? "flex-end" : "flex-start" }}><Text style={[styles.settingTitle, { color: colors.text, writingDirection: language === "ar" ? "rtl" : "ltr" }]}>{t(language, "notifications")}</Text><Text style={[styles.settingDescription, { color: colors.muted, writingDirection: language === "ar" ? "rtl" : "ltr" }]}>{t(language, "notificationsHint")}</Text></View><Switch value={settings.notificationsEnabled} onValueChange={(value) => void setNotificationsEnabled(value)} trackColor={{ false: colors.border, true: colors.primarySoft }} thumbColor={settings.notificationsEnabled ? colors.primary : colors.muted} /></View></Card>
    <Card style={styles.aboutCard}><View style={[styles.aboutLogo, { backgroundColor: colors.primary }]}><Text style={styles.aboutLogoText}>MR</Text></View><Text style={[styles.aboutTitle, { color: colors.text }]}>{t(language, "about")}</Text><Text style={[styles.aboutText, { color: colors.muted, writingDirection: language === "ar" ? "rtl" : "ltr" }]}>{t(language, "aboutText")}</Text><Text style={[styles.version, { color: colors.primary }]}>{t(language, "version")}</Text><Text style={[styles.package, { color: colors.muted }]}>com.mauriresults.app</Text></Card>
  </ScrollView>;
}
const styles = StyleSheet.create({ content: { padding: 14, paddingBottom: 110, gap: 12 }, cardGap: { gap: 13 }, settingTitle: { fontSize: 15, fontWeight: "900" }, settingDescription: { marginTop: 5, fontSize: 10, fontWeight: "700", lineHeight: 17 }, choices: { flexDirection: "row", gap: 8, flexWrap: "wrap" }, choice: { minHeight: 42, flexGrow: 1, borderWidth: 1, borderRadius: 14, paddingHorizontal: 12, alignItems: "center", justifyContent: "center" }, choiceText: { fontSize: 11, fontWeight: "900" }, switchRow: { gap: 14, alignItems: "center" }, aboutCard: { alignItems: "center", paddingVertical: 26 }, aboutLogo: { width: 72, height: 72, borderRadius: 23, alignItems: "center", justifyContent: "center" }, aboutLogoText: { color: "#FFFFFF", fontSize: 25, fontWeight: "900" }, aboutTitle: { marginTop: 15, fontSize: 19, fontWeight: "900" }, aboutText: { marginTop: 8, maxWidth: 330, textAlign: "center", fontSize: 11, fontWeight: "700", lineHeight: 19 }, version: { marginTop: 13, fontSize: 11, fontWeight: "900" }, package: { marginTop: 5, fontSize: 9, fontWeight: "700" } });
