import React, { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useApp } from "../context/AppContext";
import { fetchAnalytics } from "../lib/api";
import { t } from "../lib/i18n";
import { isBacExam, isNoTrackExam, TRACK_LABELS, textValue } from "../lib/result";
import type { AnalyticsData, Exam } from "../types";
import { EmptyState, MetricCard, Pill, SectionTitle } from "../components/ui";
const TRACK_ORDER = ["SN", "M", "LO", "LM"];
function formatNumber(value: unknown, language: "ar" | "fr", digits = 0) { const number = Number(value); if (!Number.isFinite(number)) return "—"; return number.toLocaleString(language === "ar" ? "ar-MR" : "fr-FR", { maximumFractionDigits: digits, minimumFractionDigits: digits }); }
export function StatsScreen() {
  const { colors, language, exams, isOnline } = useApp(); const [selected, setSelected] = useState<Exam | null>(exams[0] || null); const [data, setData] = useState<AnalyticsData | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!selected && exams.length) setSelected(exams[0] || null); }, [exams, selected]);
  useEffect(() => { if (!selected || !isOnline) return; let active = true; setLoading(true); setError(""); fetchAnalytics(selected.source_key).then((response) => { if (active) setData(response); }).catch(() => { if (active) { setData(null); setError(t(language, "error")); } }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [selected?.source_key, isOnline, language]);
  const trackStats = useMemo(() => { if (!selected || !isBacExam(selected) || isNoTrackExam(selected)) return []; const rows = Array.isArray(data?.trackStats) ? [...data!.trackStats!] : []; return rows.sort((a, b) => { const aCode = String(a.track || a.label || "").toUpperCase(); const bCode = String(b.track || b.label || "").toUpperCase(); const ai = TRACK_ORDER.indexOf(aCode); const bi = TRACK_ORDER.indexOf(bCode); if (ai === -1 && bi === -1) return aCode.localeCompare(bCode); if (ai === -1) return 1; if (bi === -1) return -1; return ai - bi; }); }, [data, selected]);
  const stats = data?.stats; const passRate = stats?.total ? (Number(stats.passed || 0) / Number(stats.total)) * 100 : 0;
  return <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><SectionTitle title={t(language, "analytics")} /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.examChips} style={styles.examScroller}>{exams.map((exam) => { const active = selected?.source_key === exam.source_key; return <Pressable key={exam.source_key} onPress={() => setSelected(exam)} style={[styles.examChip, { backgroundColor: active ? colors.primary : colors.surface, borderColor: active ? colors.primary : colors.border }]}><Text style={[styles.examChipText, { color: active ? "#FFFFFF" : colors.text }]} numberOfLines={1}>{language === "ar" ? exam.title_ar : exam.title_fr}</Text></Pressable>; })}</ScrollView>
    {!isOnline ? <EmptyState icon="📡" title={t(language, "offline")} /> : null}{loading ? <View style={styles.loading}><ActivityIndicator size="large" color={colors.primary} /><Text style={[styles.loadingText, { color: colors.muted }]}>{t(language, "loading")}</Text></View> : null}{error && !loading ? <EmptyState icon="⚠️" title={error} /> : null}{!selected && !loading ? <EmptyState icon="📊" title={t(language, "pickExamForStats")} /> : null}
    {selected && data && !loading ? <><View style={styles.metrics}><MetricCard icon="👥" label={t(language, "total")} value={formatNumber(stats?.total, language)} /><MetricCard icon="✅" label={t(language, "passed")} value={formatNumber(stats?.passed, language)} />{!stats?.isConcours ? <MetricCard icon="📈" label={t(language, "average")} value={formatNumber(stats?.average, language, 2)} /> : <MetricCard icon="🏆" label={t(language, "highest")} value={formatNumber(stats?.highest, language, 2)} />}<MetricCard icon="%" label={t(language, "passRate")} value={`${formatNumber(passRate, language, 1)}%`} /></View>
      {trackStats.length ? <View style={styles.section}><SectionTitle title={t(language, "tracks")} /><View style={styles.list}>{trackStats.map((item, index) => { const code = String(item.track || item.label || "").toUpperCase(); const label = TRACK_LABELS[code]?.[language]; return <View key={`${code}:${index}`} style={[styles.statRow, { backgroundColor: colors.surface, borderColor: colors.border, flexDirection: language === "ar" ? "row-reverse" : "row" }]}><View style={{ flex: 1, alignItems: language === "ar" ? "flex-end" : "flex-start" }}><Text style={[styles.statName, { color: colors.text }]}>{label ? `${code} — ${label}` : code}</Text><Text style={[styles.statMeta, { color: colors.muted }]}>{t(language, "total")}: {formatNumber(item.total, language)}</Text></View><Pill text={`${formatNumber(item.passRate, language, 1)}%`} tone="green" /></View>; })}</View></View> : null}
      {Array.isArray(data.regionStats) && data.regionStats.length ? <View style={styles.section}><SectionTitle title={t(language, "regions")} /><View style={styles.list}>{data.regionStats.slice(0, 12).map((item, index) => <View key={`${String(item.label || item.wilaya)}:${index}`} style={[styles.statRow, { backgroundColor: colors.surface, borderColor: colors.border, flexDirection: language === "ar" ? "row-reverse" : "row" }]}><View style={{ flex: 1, alignItems: language === "ar" ? "flex-end" : "flex-start" }}><Text style={[styles.statName, { color: colors.text }]} numberOfLines={1}>{textValue(item.label || item.wilaya)}</Text><Text style={[styles.statMeta, { color: colors.muted }]}>{t(language, "total")}: {formatNumber(item.total, language)}</Text></View><Pill text={`${formatNumber(item.passRate, language, 1)}%`} tone="gold" /></View>)}</View></View> : null}
      {Array.isArray(data.topStudents) && data.topStudents.length ? <View style={styles.section}><SectionTitle title={t(language, "topStudents")} /><View style={styles.list}>{data.topStudents.slice(0, 12).map((student, index) => { const track = selected && !isNoTrackExam(selected) ? String(student.track || "") : ""; return <View key={`${String(student.id || student.name)}:${index}`} style={[styles.topper, { backgroundColor: colors.surface, borderColor: colors.border, flexDirection: language === "ar" ? "row-reverse" : "row" }]}><View style={[styles.rankCircle, { backgroundColor: index < 3 ? `${colors.gold}25` : colors.primarySoft }]}><Text style={[styles.rankText, { color: index < 3 ? colors.gold : colors.primary }]}>{index + 1}</Text></View><View style={{ flex: 1, alignItems: language === "ar" ? "flex-end" : "flex-start" }}><Text style={[styles.topperName, { color: colors.text, writingDirection: language === "ar" ? "rtl" : "ltr" }]} numberOfLines={2}>{textValue(student.name)}</Text><Text style={[styles.topperMeta, { color: colors.muted }]}>{textValue(student.id)}{track ? ` • ${track}` : ""}</Text></View><Text style={[styles.topperScore, { color: colors.primary }]}>{formatNumber(student.MOD ?? student.score ?? student.total, language, 2)}</Text></View>; })}</View></View> : null}</> : null}
  </ScrollView>;
}
const styles = StyleSheet.create({ content: { padding: 14, paddingBottom: 110 }, examScroller: { marginBottom: 14 }, examChips: { gap: 8, paddingHorizontal: 1 }, examChip: { maxWidth: 245, minHeight: 42, borderWidth: 1, borderRadius: 15, paddingHorizontal: 13, alignItems: "center", justifyContent: "center" }, examChipText: { fontSize: 11, fontWeight: "900" }, loading: { paddingVertical: 40, alignItems: "center", gap: 10 }, loadingText: { fontSize: 11, fontWeight: "800" }, metrics: { flexDirection: "row", flexWrap: "wrap", gap: 10, justifyContent: "space-between" }, section: { marginTop: 24 }, list: { gap: 9 }, statRow: { minHeight: 65, borderWidth: 1, borderRadius: 18, padding: 12, alignItems: "center", gap: 10 }, statName: { fontSize: 12, fontWeight: "900" }, statMeta: { marginTop: 4, fontSize: 9, fontWeight: "700" }, topper: { minHeight: 72, borderWidth: 1, borderRadius: 19, padding: 11, alignItems: "center", gap: 11 }, rankCircle: { width: 40, height: 40, borderRadius: 14, alignItems: "center", justifyContent: "center" }, rankText: { fontSize: 15, fontWeight: "900" }, topperName: { fontSize: 12, fontWeight: "900", lineHeight: 18 }, topperMeta: { marginTop: 4, fontSize: 9, fontWeight: "700" }, topperScore: { fontSize: 14, fontWeight: "900" } });
